chore: working deploy scripts

diff --git a/bin/changelog-to-json b/bin/changelog-to-json
--- a/bin/changelog-to-json
+++ b/bin/changelog-to-json
@@ -3,7 +3,7 @@
 NAME="$(basename $0)"
 
 version() {
-  echo "${VERSION:-0.0.0}"
+  echo "0.2.4"
 }
 
 usage() {
@@ -30,7 +30,7 @@ EOF
 }
 
 function die() {
-  echo "$@" >&2
+  echo -e "$@" >&2
   exit 1
 }
 
@@ -48,34 +48,49 @@ function get-changelog-pair() {
 }
 
 function changelog-to-json() {
-  local options
-
-  options=$(getopt -o hv -l help,version,rpc-url: --name "$NAME" -- "$@")
-  eval set -- "$options"
-
   local rpc_url="$ETH_RPC_URL"
 
-  while true; do
-    case "$1" in
-      -h|--help)
+  local optspec="hv-:"
+
+  while getopts "$optspec" OPT; do
+    # support long options: https://stackoverflow.com/a/28466267/519360
+    if [ "$OPT" = "-" ]; then   # long option: reformulate OPT and OPTARG
+      OPT="${OPTARG%%=*}"       # extract long option name
+      OPTARG="${OPTARG#$OPT}"   # extract long option argument (may be empty)
+      OPTARG="${OPTARG#=}"      # if long option argument, remove assigning `=`
+    fi
+
+    case "$OPT" in
+      h | help)
         usage
         exit 0
         ;;
-      -v|--version)
+      v | version)
         version
         exit 0
         ;;
-      --rpc-url)
-        rpc_url="$2"
-        shift
+      rpc-url)
+        [ -z "$OPTARG" ] && {
+          echo -e "\n--rpc-url option is missing its argument\n"
+          usage
+          exit 1
+        }
+        rpc_url="$OPTARG"
         ;;
-      --)
-        shift
-        break
+      ??*)
+        # bad long option
+        echo -e "\nIllegal option --$OPT\n"
+        usage
+        exit 1
+        ;;
+      ?)
+        echo -e "\nIllegal option -${BOLD}$OPTARG${OFF}\n"
+        usage
+        exit 1
         ;;
     esac
-    shift
   done
+  shift $((OPTIND-1))
 
   local changelog
 
@@ -95,7 +110,7 @@ function changelog-to-json() {
     # Notice there is an appended `,` above. That is because of a POSIX bug described here:
     # https://mywiki.wooledge.org/BashPitfalls#IFS.3D.2C_read_-ra_fields_.3C.3C.3C_.22.24csv_line.22
     wait
-  } | sort)
+  })
   pairs="{\"key\":\"version\",\"value\":\"$(seth --rpc-url="$rpc_url" call $changelog 'version()(string)')\"} ${pairs}"
 
   jq -s 'from_entries' <<<"$pairs"
diff --git a/bin/json-to-env b/bin/json-to-env
--- a/bin/json-to-env
+++ b/bin/json-to-env
@@ -3,7 +3,7 @@
 NAME="$(basename $0)"
 
 version() {
-  echo "${VERSION:-0.0.0}"
+  echo "0.2.4"
 }
 
 usage() {
@@ -29,6 +29,7 @@ Examples:
   $NAME -x /path/to/file.json     Export the variables (\`export VAR=VALUE\`)
 
   $NAME -f /path/to/file.json     Can use the -f option
+  $NAME --file=/path/to/file.json Do not forget the = sign when using the long form
   $NAME /path/to/file.jsoni       Or simply a positional argument
 
   $NAME <<< '{"VAR":"VALUE"}'     JSON literal
@@ -36,40 +37,57 @@ EOF
 }
 
 json-to-env() {
-  local options
   local file
   local exports=false
 
-  options=$(getopt -o f:hxv -l file:,help,export,version --name "$NAME" -- "$@")
-  eval set -- "$options"
+  local optspec="hxvf:-:"
 
-  while true; do
-    case "$1" in
-      -h|--help)
+  while getopts "$optspec" OPT; do
+    # support long options: https://stackoverflow.com/a/28466267/519360
+    if [ "$OPT" = "-" ]; then   # long option: reformulate OPT and OPTARG
+      OPT="${OPTARG%%=*}"       # extract long option name
+      OPTARG="${OPTARG#$OPT}"   # extract long option argument (may be empty)
+      OPTARG="${OPTARG#=}"      # if long option argument, remove assigning `=`
+    fi
+
+    case "$OPT" in
+      h | help)
         usage
         exit 0
         ;;
-      -v|--version)
+      v | version)
         version
         exit 0
         ;;
-      -x|--export)
+      x | export)
         exports=true
         ;;
-      -f|--file)
-        file="$2"
-        shift
+      f | file)
+        [ -z "$OPTARG" ] && {
+          echo -e "\n--file option is missing its argument\n"
+          usage
+          exit 1
+        }
+        file="$OPTARG"
         ;;
-      --)
-        shift
-        break
+      ??*)
+        # bad long option
+        echo -e "\nIllegal option --$OPT\n"
+        usage
+        exit 1
+        ;;
+      ?)
+        echo -e "\nIllegal option -${BOLD}$OPTARG${OFF}]\n"
+        usage
+        exit 1
         ;;
     esac
-    shift
   done
+  shift $((OPTIND-1))
 
   # If -f/--file is not used, <file> is the first positional argument
   # If it's not given or empty, then the script should read from stdin
+
   file="${file:-${1:-/dev/stdin}}"
   local output=$(
     jq -r 'to_entries | map(.key + "|" + (.value | tostring)) | .[]' "$file" |
